name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### Via vim-plug
          ```vim
          Plug 'yourusername/zzvim-R'
          ```
          
          ### Via Vundle
          ```vim
          Plugin 'yourusername/zzvim-R'
          ```
          
          ### Manual Installation
          Copy `plugin/zzvim-R.vim` and `doc/zzvim-R.txt` to your Vim runtime path.
          
        draft: false
        prerelease: false